//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpertWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BarcodeItem
    {
        public int ID { get; set; }
        public string Upc { get; set; }
        public string Ean { get; set; }
        public string Category { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public string Manufacturer { get; set; }
        public string Description { get; set; }
        public string Title { get; set; }
    }
}
